services:

  backend:
    build: ./backend
    container_name: backend-container
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      PORT: 3000
      DB_USER: admin
      DB_HOST: postgres
      DB_NAME: docudb
      DB_PASSWORD: password
      DB_PORT: 5432
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: frontend-container
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  postgres:
    image: postgres:16
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: docudb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: