apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend
  namespace: docu-scale

spec:
  replicas: 1

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
        - name: frontend

          image: 084847996093.dkr.ecr.eu-north-1.amazonaws.com/docu-frontend:latest

          ports:
            - containerPort: 5173